Fixed AttributeError: 'NoneType' object has no attribute 'find_all'
Created a check for when option_tags is None (that is, when html.find("select") returns None).  The find() method returns the result of the tree traversal; if it finds nothing, it returns None.